pub mod channel;
mod connection;
mod header;
pub mod inner_server;
mod int_buffer;
mod send_buffer;
mod sequence_buffer;
pub mod server;
pub mod udp;
pub const BUFFER_SIZE: u32 = 1024;
pub const MAGIC_NUMBER_HEADER: [u8; 4] = [1, 27, 25, 14];
